name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  container-test-job:
    runs-on: self-hosted
    container:
      image: ubuntu:latest
    steps:
      - name: PWD check
        run: sleep 300


