name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  container-test-job:
    runs-on: Linux
    container:
      image: ubuntu:latest
    steps:
      - name: Check for dockerenv file
        run: pwd


